version: '3.4'

services:

  homeassistant:
    container_name: ha
    image: homeassistant/home-assistant:latest
    env_file: ./.env
    volumes:
      - /media/shared/home/$USER/docker/containers/ha:/config
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure
    network_mode: host
    environment:
      - UDEV=1
    privileged: true
    devices:
      - /dev/ttyACM0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$ha_port1"]
      interval: 30s
      timeout: 10s
      retries: 6
    depends_on:
      - mqtt
      - zwave2mqtt

  mqtt:
    container_name: mqtt
    restart: on-failure
    image: eclipse-mosquitto:latest
    env_file: ./.env
    user: 1883:1883
    environment:
      - PGID=1883
      - PUID=1883
    volumes:
      - /media/shared/mosquitto/config:/mosquitto/config:rw
      - /media/shared/mosquitto/data:/mosquitto/data:rw
      - /media/shared/mosquitto/log:/mosquitto/log:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${mqtt_port1}:${mqtt_port1}"
      - "${mqtt_port2}:${mqtt_port2}"

  tasmoadmin:
    container_name: tasmoadmin
    restart: on-failure
    image: raymondmm/tasmoadmin
    env_file: ./.env
    volumes:
      - tasmoadmin_data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${tasmoadmin_port1}:${tasmoadmin_port2}"

  zwave2mqtt:
    container_name: zwave2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: unless-stopped
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - /media/shared/store:/usr/src/app/store
    ports:
      - '8091:8091'
      - '3001:3000'

volumes:
  tasmoadmin_data:
